#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/side-route-daemon

start_service() {
	local enabled
	config_load sideroute
	config_get_bool enabled config enabled 0

	if [ "$enabled" -ne 1 ]; then
		logger -t sideroute "Service is disabled in /etc/config/sideroute"
		return 0
	fi

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root
	procd_close_instance
	logger -t sideroute "Side-route daemon started."
}

service_triggers() {
	procd_add_reload_trigger "sideroute"
}

reload_service() {
	restart
}

stop_service() {
	logger -t sideroute "Side-route daemon stopped."
}
